<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promesas</title>
</head>
<body>
    <h1>Promesas</h1>
    <script>
        /*
        ---------------- Promesas ------------------
        * Se pueden ver como un if - else, si esta se cumple se ejecutaria el resolve. Por otro lado, si no se llega a cumplir se ejecutará el reject.

        * Las promesas se utilizan cuando se tiene la concatenación de varios procesos asíncronos

        * A diferencia de las callbacks, con las promesas en el catch ya valida el error en cualquiera de sus llamados con el catch

        function cuadradoCallback(value, callback) {
            //Settiomeout va a simular el ir y consumir una API externa
            setTimeout(() => {
                callback(value, value * value);
            }, 0 | Math.random() * 1000);
        }
        */

        function cuadradoPromise(value){
            if (typeof value !== 'number')
            //Si el valor no es un numero
                return Promise.reject(`Error, el valor ingresado "${value}" no es un numero`);
            //Se crea un objeto de tipo promise, el cual recibe una funcion con los 2 valores "resolve" y "reject"
            return new Promise((resolve, reject) => {
                //se pasa lo del settimeout
                setTimeout(() => {
                    //El resolve es como el return positivo de la promesa
                    resolve({
                        //Value como el parametro que se pase y result el resultado de la operacion
                        value: value,
                        result: value * value
                    });
                }, 0 | Math.random() * 1000);
            })
        }

        //Then recibe la parte positiva de la promesa
        cuadradoPromise(0)
            .then((obj) => {
                console.log('Inicia Promise');
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromise(1);
            })
            //Se concatena otro
            .then((obj) => {
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromise(2);
            })
            .then((obj) => {
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromise(3);
            })
            .then((obj) => {
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromise("4");
            })
            .then((obj) => {
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromise(5);
            })
            //Como solo quiero que sea hasta 5 no debo mandar otro return
            .then((obj) => {
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                console.log('Fin de la promesa');
                
            })
            //Catch atrapa el error resultante del reject
            .catch(err => console.error(err));
            
    </script>
</body>
</html>